#!/bin/bash

ABCERT_NAME=$(basename "${BASH_SOURCE[0]}")

ABCERT_VERSION="AbCert 0.2.2"

ABCERT_HELP="\
Usage: $ABCERT_NAME COMMAND

Commands:
  install     Install certificates to the operating system
  install4j   Install certificates to the java keystore
  test        Test the accessibility of various kinds of HTTPS links
  version     Show AbCert version

Run '$ABCERT_NAME COMMMAND --help' for more information on a command.
"

ABCERT_INSTALL_HELP="\
Usage: $ABCERT_NAME install

Install certificates to the operating system
"

ABCERT_INSTALL4J_HELP="\
Usage: $ABCERT_NAME install4j [OPTIONS]

Install certificates to the java keystore

Options:
  -k, --keystore PATH         keystore path
  -p, --storepass PASSWORD    keystore password
"

ABCERT_TEST_HELP="\
Usage: $ABCERT_NAME test [OPTIONS]

Test the accessibility of various kinds of HTTPS links

To test the accessibility of external links through the proxy, environment
variables ABCERT_TEST_PROXY_NAME and ABCERT_TEST_PROXY_PASSWORD must be set.
If they are unset, relevant tests will be skipped.

Options:
      --color COLOR          colorize the output; COLOR can be 'auto', 'true',
                             or 'false' (default: 'auto')
"

ABCERT_PEMS_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/pems
ABCERT_IS_COMPILED=true

HuaweiBPITRootCA="\
-----BEGIN CERTIFICATE-----
MIIF0TCCA7mgAwIBAgIRIBkSEhgnCT3Xo17fA7TGRAEwDQYJKoZIhvcNAQELBQAw
QTELMAkGA1UEBhMCQ04xFDASBgNVBAoTC0h1YXdlaSBCUElUMRwwGgYDVQQDExNI
dWF3ZWkgQlBJVCBSb290IENBMB4XDTE5MTIxMjEwMjcwOVoXDTQ5MTIwNDEwMjcw
OVowQTELMAkGA1UEBhMCQ04xFDASBgNVBAoTC0h1YXdlaSBCUElUMRwwGgYDVQQD
ExNIdWF3ZWkgQlBJVCBSb290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEA5TN8gXbdYhtk+IQ7JYArfsaiyQJfnI6QOA+iqRZlktcFoE7p2xPscKb2
tkrm+dZIa08cUa7nvbFOcQ1kuY9xGBpyuPXTzbkS+B7LkzgBh7ofZRh5AB++aNYG
6mYW8unTrihj9cGU/kAIpmew6Uer78W3hY6slm0orw76dXgxpKqy+etA3XwiBHV0
bvuodPxJG1ppBLxsVeF3Uy0PUAgWXzI0E3PfSQg8vcp5hGDi9ly5Rrrte2TQUSVX
mqzQfS6Q9bPOh7Vh8IWCYNJHT+wQ4/vZfzQtbwxRapaimG7JArxksBzcBnyIjB6W
vEPUeGBhxPaSehhVBJSKTkCe0X5llFPjKxRqF0Jj3++q5kMSPfc33Y7Oz/CKl4W8
uEdnRFciBDsb89cSvFbnYcz025RXSAZnxmXj9/tBbNNSv6r04xRHZQ7PRwDQJE31
NKIs5nKZ1T180LofaBlJTCj4qx/3eaVp6YkFvuyBBNvafjbNNmHfHvd3lG940w49
aKevpwKi1wblLks/ERBPwMHO9tacA2DIqD5eue3ukKTpXN+/K2UbO5DBl0c9/pM7
MA85VAl/R/+sJbWpQe1p1Mw+hRoMg3bYID3JtnNpc9p2Uy8uiHcb4OLbc4MmPiLd
n4fkdi1RRuvf3wXlZQ6zi5nG5+9Iz09Q3G9XFETDpkL1gX3QYhsCAwEAAaOBwzCB
wDAPBgNVHRMBAf8EBTADAQH/MG8GA1UdIARoMGYwZAYEVR0gADBcMFoGCCsGAQUF
BwICME4eTABoAHQAdABwADoALwAvAHAAawBpAC4AYgBwAGkAdAAuAGgAdQBhAHcA
ZQBpAC4AYwBvAG0ALwBjAHAAcwAvAGMAcABzAC4AcABkAGYwHQYDVR0OBBYEFIwD
5HOStF9uycex9u2gsIYPN5FWMAsGA1UdDwQEAwIBhjAQBgkrBgEEAYI3FQEEAwIB
ADANBgkqhkiG9w0BAQsFAAOCAgEAqLEarf6CVnRbhgkk5oVhlfJwbzeN7L6EkCmO
UcpUC9lzU0w4cZ03YgsRgATzWepb7lPYr5SmZoGgL+99fG60wEcmU7zNhM2HitBQ
ChOgdIFrfT+rCE6RzH3SNufCjs6gSw9mbqR+/dFOnDsIbJ2cD6hvdBXvQRH9ncws
ojQ4OJRlMEhVuY29SLscZhSu6DsRxLesubRkphtpyo9bDSFkRi6Yz9X8Gh3aaQHI
GUfez7C7UGn3EF0Gq297FweeoExUgc1JZeHCdSO0NhgqHHqryyJrOu9Si/NDmtN3
NETTq4dppMg2zFQ0WpjoxhNbgkRxvh9gL1Ai6XaBFwhDvkc7aiKtqQ+MXp7L2lAs
WS2b8qdUsHaoMKCffuBlpJeIXyzbkcd8yK2m/cBs0ZxxEl59Dup5usHe/k1IMGTV
Cxdz6lLazpgo704AVkNLseYCSXiQ2c/NP+hplZiUJXHfJ4a71838PbASCJMXxgy2
gu4MbiYEwUb56ipV59M8JyGqT0cRUDWyQfPmuypq0HtZnC+sBRCrToXPFLB4Dl5n
7CO/dOz0xmnQkSY9fGi15zu9yPhNf0Qv7edLLq2kPaAwlIl2Ppfsl3pwSWljRaaV
EHJ+5FHOitT8Ph1076aQHH3crZWJstjDXr3kaoU4UspM3CSjXaoIPnU6BjBYj38t
BGyATOc=
-----END CERTIFICATE-----
"

HuaweiITRootCA="\
-----BEGIN CERTIFICATE-----
MIIFrDCCA5SgAwIBAgIQMvvk+dsqBptBSeXEBBFiRjANBgkqhkiG9w0BAQsFADAw
MRIwEAYDVQQKEwlIdWF3ZWkgSVQxGjAYBgNVBAMTEUh1YXdlaSBJVCBSb290IENB
MB4XDTEzMDkyOTA2NTI0NFoXDTQ1MDkyOTA3MDIyNlowMDESMBAGA1UEChMJSHVh
d2VpIElUMRowGAYDVQQDExFIdWF3ZWkgSVQgUm9vdCBDQTCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAKCa/7dGb1qmhYyDSwxekqVUcKRaAJWi3n65E9KD
5hYb6oZkCaTUTwX+/m6oT5tj/TLow99Zwm/xcZ4e1xh2inqkWDPKdRRuiAtJLu8T
JoGl0Dlql2vhQvZPIAZOis8+j4sKZrFPNUjVp18KH0Dpgiu/oLlRjAh0+naMp75E
/PAxAmPKW9qNAY60QTG2JzyoqSj6G40ss4cx5JouCCaqdvFSKFf3qSbFdMk0o8az
w3ESmo4vt2SmwN4NC5XJ5sGVTG5yRnqdVgwvC6sgodclrDuAFXpSrMW4LZlVT9yA
PXMaZFrjrzi7cPSkLxhhE0shwv+nvvaM1k/83naL3675DTNfeni7Hw1lctfs0Lu9
o+P8A/BrlbGrWXfl7V16w5fsOkB/vY9n9H8Wvoj2jChOolxbb1Xu9Lzlm+L9I/4H
Vc8oFlIdfapZ/Y3pL+sqsPHRazpz114t9wDKkjCgileEm+LEHmqbA+9fioeSxYzT
PDeP9M0P3BV05/MVBgv5xP1xNrCZwRAejcsrewty2pCRbVfAZS8aQ5u7QxWRl3Ow
OryZxWzt/KCO+IUmtQ6VHN5kEawrYBns44XCyZ9lOZWEBsuKr2spAMSZt/ZD2Bny
KiHZLrcJlOlV8lZTEJknPj7Nux/hkHd7yhlrWF4UQPRJkmlcy2XOEurzWk3wKtHP
d44pAgMBAAGjgcEwgb4wCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYD
VR0OBBYEFNpkGmV7FNjwnRjj8612vZMEWkqNMBAGCSsGAQQBgjcVAQQDAgEAMG0G
A1UdIARmMGQwYgYEVR0gADBaMFgGCCsGAQUFBwICMEweSgBoAHQAdABwADoALwAv
AGgAdwBpAHQAcABrAGkALgBoAHUAYQB3AGUAaQAuAGMAbwBtAC8AYwBwAHMALwBj
AHAAcwAuAHAAZABmMA0GCSqGSIb3DQEBCwUAA4ICAQCN/UHKuI4FQV8O5HJ7yr/I
sfPo4v9aKpyAVbYPZur3+tR4IrQ19LjmAdczQm0f4lVIEwAxK7v8tTuBq36//qtf
VG5H7OmDYDdatAHgrqQwxMmbzN5+mbpO+aSf/5a03BS5lweEFTBXvqCtGvKJb4N+
umyNpxBYT/2JkauLmvk/NPbU8JLRPnmjRlXsMHB/vXY2BB8OIn0AnGdq8DS4HAm9
/o4DU818pBXHIWgkkgsfOCRU3UeoZ1JufmXvvxrM78LLWhilHpyZR6/lR/PV0Bjd
7wipRd8jBkQFIZ2X4ZFodM1NDtKg4mroajp2SCDUeE1R2HcNpkz5lcgarSLf30V7
zPENdV3yb2vk1BGRIqBxcxqt36L7XnUZPBGmHDqX3j6jIVWvw0e0Pdzv+pftBwGr
8GavQUryUAXrcHxjdQgQMp82CmORrhLsJ79rpYRQcxV/Iglpzxsbg5GOrkiA2o2/
5dGf2hfOYnP3T93TdM7DsoinEMBursJkeo5sQBeVE+kFNYhqJ+12QNvhdigqa96Y
b0h7dFqZxebJFEIUVUfx6BJNmlz/Ax/USWIwWTmelJk4Mo7mAM6qgApEN+wFG63t
Sk94Y1naBA9ey4wyfwPTSqNJ2LFy7SCiUJTTVxWd6/T49ScjIevTZSuMezjqcB4b
7THUftXuufrVtAQ7iSP3IQ==
-----END CERTIFICATE-----
"

HuaweiWebSecureInternetGatewayCA="\
-----BEGIN CERTIFICATE-----
MIID2TCCAsGgAwIBAgIJALQPO9XxFFZmMA0GCSqGSIb3DQEBCwUAMIGCMQswCQYD
VQQGEwJjbjESMBAGA1UECAwJR3VhbmdEb25nMREwDwYDVQQHDAhTaGVuemhlbjEP
MA0GA1UECgwGSHVhd2VpMQswCQYDVQQLDAJJVDEuMCwGA1UEAwwlSHVhd2VpIFdl
YiBTZWN1cmUgSW50ZXJuZXQgR2F0ZXdheSBDQTAeFw0xNjA1MTAwOTAyMjdaFw0y
NjA1MDgwOTAyMjdaMIGCMQswCQYDVQQGEwJjbjESMBAGA1UECAwJR3VhbmdEb25n
MREwDwYDVQQHDAhTaGVuemhlbjEPMA0GA1UECgwGSHVhd2VpMQswCQYDVQQLDAJJ
VDEuMCwGA1UEAwwlSHVhd2VpIFdlYiBTZWN1cmUgSW50ZXJuZXQgR2F0ZXdheSBD
QTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANk9kMn2ivB+6Lp23PIX
OaQ3Z7YfXvBH5HfecFOo18b9jC1DhZ3v5URScjzkg8bb616WS00E9oVyvcaGXuL4
Q0ztCwOszF0YwcQlnoLBpAqq6v5kJgXLvGfjx+FKVjFcHVVlVJeJviPgGm4/2FLh
odoreBqPRAfLRuSJ5U+VvgYipKMswTXh7fAK/2LkTf1dpWNvRsoXVm692uFkGuNx
dCdUHYCI5rl6TqMXht/ZINiclroQLkd0gJKhDVmnygEjwAJMMiJ5Z+Tltc6WZoMD
lrjETdpkY6e/qPhzutxDJv5XH9nXN33Eu9VgE1fVEFUGequcFXX7LXSHE1lzFeae
rG0CAwEAAaNQME4wHQYDVR0OBBYEFDB6DZZX4Am+isCoa48e4ZdrAXpsMB8GA1Ud
IwQYMBaAFDB6DZZX4Am+isCoa48e4ZdrAXpsMAwGA1UdEwQFMAMBAf8wDQYJKoZI
hvcNAQELBQADggEBAKN9kSjRX56yw2Ku5Mm3gZu/kQQw+mLkIuJEeDwS6LWjW0Hv
3l3xlv/Uxw4hQmo6OXqQ2OM4dfIJoVYKqiLlBCpXvO/X600rq3UPediEMaXkmM+F
tuJnoPCXmew7QvvQQvwis+0xmhpRPg0N6xIK01vIbAV69TkpwJW3dujlFuRJgSvn
rRab4gVi14x+bUgTb6HCvDH99PhADvXOuI1mk6Kb/JhCNbhRAHezyfLrvimxI0Ky
2KZWitN+M1UWvSYG8jmtDm+/FuA93V1yErRjKj92egCgMlu67lliddt7zzzzqW+U
QLU0ewUmUHQsV5mk62v1e8sRViHBlB2HJ3DU5gE=
-----END CERTIFICATE-----
"

HWBPITEnterpriseCA1="\
-----BEGIN CERTIFICATE-----
MIIFKzCCAxOgAwIBAgISIBkSEiJDGFThxLBdyPdOyAERMA0GCSqGSIb3DQEBCwUA
MEExCzAJBgNVBAYTAkNOMRQwEgYDVQQKEwtIdWF3ZWkgQlBJVDEcMBoGA1UEAxMT
SHVhd2VpIEJQSVQgUm9vdCBDQTAeFw0xOTEyMTIxNDQzMThaFw0zNDEyMDgxNDQz
MThaMEQxCzAJBgNVBAYTAkNOMRQwEgYDVQQKEwtIdWF3ZWkgQlBJVDEfMB0GA1UE
AxMWSFdCUElUIEVudGVycHJpc2UgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBANMfNnRnNyn0OGfd4aHCDc9/bi+4LSwF/n0cGCIZ6cec7aVfEQgl
+a15ncqsEg9eywhhVmW1eSTfJ2e0m3KmUgNRgOLty41wbViAJBNQZ5/m9OLoonSF
stpl1rX3dclkuC0b0ttna8bXOhnoqmW3x78102M+wQS1lASxCwf65V5bkNpQhnVR
1nDT6tnjuUE8BTvFVje8qvynt9jtdLjlqE3CD7wsaO4JGMrXshSrcCBCGVKoPnD4
ie0xu0wGV0tD8a10GrX0FLF1fRohxHPRrsFrLy2RCQ2VFu3V+bC4zFmWv7LFrLfr
6/qK8HipeWASWKNIXx0jO/TGC31hVFr2zN0CAwEAAaOCARgwggEUMB8GA1UdIwQY
MBaAFIwD5HOStF9uycex9u2gsIYPN5FWMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
QwBBMB0GA1UdDgQWBBS0q5zDvbzNySKkA8TKZNCcZaghsjAPBgNVHRMBAf8EBTAD
AQH/MAsGA1UdDwQEAwIBxjA9BgNVHR8ENjA0MDKgMKAuhixodHRwOi8vcGtpLmJw
aXQuaHVhd2VpLmNvbS9jcmwvaHdicGl0cmNhLmNybDBIBggrBgEFBQcBAQQ8MDow
OAYIKwYBBQUHMAKGLGh0dHA6Ly9wa2kuYnBpdC5odWF3ZWkuY29tL2FpYS9od2Jw
aXRyY2EuY3J0MBAGCSsGAQQBgjcVAQQDAgEAMA0GCSqGSIb3DQEBCwUAA4ICAQCN
zgJwqTCDVJqgk0ljHYjlYjLnbptaVxHzTY/dZZy+Xlz5hL2uvW83V0/Vm4xVzteS
zxC03xJ4xUJ/2hD6pzYa8pP3ygQ/ZhOVHshyQDZjTi/HedwmKZvnY5AwBY4wWW33
p3G1PgqZR66pUc2lZCkNaqy9mZsig/MomrOG5jhKKo7XiiUKQdrjQ0YaYaz3QEBS
T9zLIcTxmsuaHT4YSzr2nVOQVluw2G2YZgsok5HRxZRJTxcDRth8Kkd02Xbhi0FH
3kytsheeqPCrSkE71fpLpHxrjPsqmGe/9z8SP9Fg2Ni5RRaUnwt6U8gDsiKpnmh/
zosxMhtSffScJG4qF+Ku9wt0b4Y3TewjT7eyeAmDD7vHj3SdOI9vWxd2gYHU/XUZ
W8VWmuTNJUN/sYR3Ye0mjV8jGF7nSwuVRnTT8w2olelV/G0He9J/aChrvslzyfW8
qQUh0bincbVwVmZvUf5ajyOWUxeSsVE290u2+KyDiTMcTKt4wltccWL6sBWzlJY8
j8N+e1xJvnU/SVY4vL2wVbmLS7C5rAR8N+vKfFJXu+yRLPvxH6UMmuMKpFbJ+JxN
3HS0EZO1DrCocIyfAx6JonAYW7v/NNS7VKlcvkIatp963qpOUO6w9KqftbZ6/+19
huswA6ag/OoAyfFe1WvSxNbmqbHG1EN3Be91hc3m7w==
-----END CERTIFICATE-----
"

HWITEnterpriseCA1="\
-----BEGIN CERTIFICATE-----
MIIE5zCCAs+gAwIBAgIKEQnVLgAAAAAAAjANBgkqhkiG9w0BAQsFADAwMRIwEAYD
VQQKEwlIdWF3ZWkgSVQxGjAYBgNVBAMTEUh1YXdlaSBJVCBSb290IENBMB4XDTEz
MTAxOTE2NDYyN1oXDTI5MTAxOTE2NTYyN1owHzEdMBsGA1UEAxMUSFdJVCBFbnRl
cnByaXNlIENBIDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCgTZd
tF/7JsqJ1EzQniPUweWgiKNNNBcQ4p8mu+qag/fRtsYiEgkZW87BBhKFPSRRJGHH
UJfr6gU+f6S6T3LxrzaQHHcGjqcSNhryNaEEhT5pIOcrQQ2mKFQaB9f0LAz9BUpG
Gfi/uQe4ZpNlgXCDPf6Gynfj0ib7HMir6hNq2BYfvZAqiW7av4SuTKGlghmINZ8A
YHVn8Nkcj6XBG2uiDavDMpy1GlbqW1puvhL8gZjW7uvA/EWS5146yCfcpZqsDeoZ
oDOagFPhGZDwGkvjxoa+NOcPgUTGj3TtU0GwL4d+l5H9spA6Yq769C9CgstS9UQN
LkNOYvERhNsvXQ5JAgMBAAGjggESMIIBDjAQBgkrBgEEAYI3FQEEAwIBADAdBgNV
HQ4EFgQUprTHK1IfoHi5hilrQiYNQkXnFLswGQYJKwYBBAGCNxQCBAweCgBTAHUA
YgBDAEEwCwYDVR0PBAQDAgHGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
2mQaZXsU2PCdGOPzrXa9kwRaSo0wOgYDVR0fBDMwMTAvoC2gK4YpaHR0cDovL2h3
aXRwa2kuaHVhd2VpLmNvbS9jcmwvaHdpdHJjYS5jcmwwRQYIKwYBBQUHAQEEOTA3
MDUGCCsGAQUFBzAChilodHRwOi8vaHdpdHBraS5odWF3ZWkuY29tL2FpYS9od2l0
cmNhLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAUY0QI3lfproqsfQDzUPiOhJw6MJH
fRM2FdI0AL8wLsmkLxjhmYpQoG1nBrJwlE7oM757vrrt6SHwWEintxN3ypZKe8Wg
NtZEt36UB4BaJSkRudYwumbRp872z58q4UeayT3Mf7Enoytq5S6Lz94F9+gNP7Uq
UEbVewrz3Gr43TFE33DGuCWvwN01334rvffHGnpdhk6HTeCVC8dM748WR5MGM+Rr
r/n63huHofZ4zJLjhJ6Mw99LsT6gxLZjmngffJ1VvW0vUaqcv+GRVUIO1n39SJJi
3ZeTG1zsC9N6Abdhk0iTl627sA+DVtKUajz/w0CLYPj9iGAIWLW8JebnAbTLj2nB
6HOFgZa4P1B5jLK5X85fWKXgvotcNavnIwEW4w53xvX9cMa568SO1BUjZ2gfP1ef
QFBAaMwuL1foxtdacsMUtCMKdKTpbMMMJIi/zbEU2wJHk1oeud4u4x3jrqfS+aeg
Tg/fOavZip/huTfLr+m4CukkNOFsJ90RAynDUu//CezM1Eh1cV+p1lnpyJUwLril
nt+Oby/gVcRzidbVyjWsDXCBafYzC7giE3Q6ecxAzwJUQUBLGYGOAIMSROk2gFSE
jrvXYyjVAxKpDJPOxkaUXYB1o3SkSopNeOIu5uZMNdpDnky5rIvshz2vA8YsBr10
2Y9r1CrBbuMTE40=
-----END CERTIFICATE-----
"

declare -A ABCERT_PEMS=(
    [HuaweiBPITRootCA]="$HuaweiBPITRootCA"
    [HuaweiITRootCA]="$HuaweiITRootCA"
    [HuaweiWebSecureInternetGatewayCA]="$HuaweiWebSecureInternetGatewayCA"
    [HWBPITEnterpriseCA1]="$HWBPITEnterpriseCA1"
    [HWITEnterpriseCA1]="$HWITEnterpriseCA1"
)

ABCERT_COLOR=auto

################################################################################
#  Utility functions                                                           #
################################################################################

log() {
    local level=${1:?}
    shift
    echo "[$ABCERT_NAME][$level]" "$@" >&2
}

eprint() {
    echo "$@" >&2
}

color_eprint() {
    local color=${1:?}
    shift
    [ "$ABCERT_COLOR" = true ] && eprint -ne "$color"
    eprint "$@"
    [ "$ABCERT_COLOR" = true ] && eprint -ne "\e[0m"
}

check_notempty() {
    local value=$1
    local name=${2:?}
    if [ -z "$value" ]; then
        log ERROR "Option $name expects one argument"
        return 1
    fi
}

################################################################################
#  Wrapper functions for commands install and install4j                        #
#  Only effective in the compiled version of the current script                #
################################################################################

# Return values
#   0: Success
#   1: Failed to create temporary directory
#   2: Created temporary directory but failed to write files
setup() {
    if [ "$ABCERT_IS_COMPILED" != true ]; then
        return
    fi

    local tmpdir
    tmpdir=$(mktemp -d .tmp.pems.XXXXXXXX) || return 1
    log INFO "Created temporary directory $tmpdir"

    ABCERT_PEMS_DIR=$tmpdir

    local pem
    for pem in "${!ABCERT_PEMS[@]}"; do
        echo "${ABCERT_PEMS[$pem]}" > "$tmpdir"/"$pem".pem || return 2
    done
}

cleanup() {
    if [ "$ABCERT_IS_COMPILED" != true ]; then
        return
    fi

    rm -f "$ABCERT_PEMS_DIR"/*.pem
    rmdir "$ABCERT_PEMS_DIR" || return
    log INFO "Removed $ABCERT_PEMS_DIR"
}

install_wrapper() {
    if [ $# -eq 0 ]; then
        log ERROR "install_wrapper expects arguments"
        return 1
    fi

    local status=0
    setup || status=$?
    if [ "$status" -ne 0 ]; then
        [ "$status" -ne 1 ] && cleanup
        return "$status"
    fi

    "$@" || status=$?

    cleanup || status=$?
    return "$status"
}

################################################################################
#  Command: install                                                            #
################################################################################

source_os_release() {
    if ! . /etc/os-release; then
        log ERROR "Failed to read /etc/os-release"
        return 1
    fi

    log INFO "Operating system: ${PRETTY_NAME:-unknown}"
}

install() {
    source_os_release || return

    log INFO "Installing certificates"
    local pemfile
    if [ "$ID" = euleros ] || [ "$ID" = centos ] || [ "$ID" = openEuler ] || [ "$ID" = hce ]; then
        cp -fv "$ABCERT_PEMS_DIR"/*.pem /etc/pki/ca-trust/source/anchors/ || return
        update-ca-trust

    elif [ "$ID" = sles ] || [[ "$ID" == *suse* ]]; then
        cp -fv "$ABCERT_PEMS_DIR"/*.pem /etc/pki/trust/anchors/ || return
        update-ca-certificates

    elif [ "$ID" = ubuntu ] || [ "$ID" = debian ] || [ "$ID" = alpine ]; then
        for pemfile in "$ABCERT_PEMS_DIR"/*.pem; do
            cp -fv "$pemfile" \
                "/usr/local/share/ca-certificates/$(basename "${pemfile%.pem}.crt")" || return
        done
        update-ca-certificates

    else
        log ERROR "OS not supported (ID=$ID). Please file an issue."
        return 1
    fi
}

argparse_install() {
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help)
                eprint -n "$ABCERT_INSTALL_HELP"
                return
                ;;
            *)
                log ERROR "Unexpected argument: $1"
                return 1
                ;;
        esac
    done
    install_wrapper install
}

################################################################################
#  Command: install4j                                                          #
################################################################################

get_keystore() {
    local keytool keytool_dir paths path
    keytool=$(readlink -f "$(which keytool)") || return
    keytool_dir=$(dirname "$keytool") || return

    paths=(
        "$keytool_dir"/../lib/security/cacerts
        "$keytool_dir"/../jre/lib/security/cacerts
    )
    for path in "${paths[@]}"; do
        if [ -f "$path" ]; then
            readlink -f "$path"
            return
        fi
    done

    return 1
}

install4j() {
    local keystore=$1
    local storepass=${2:-changeit}

    if [ -z "$keystore" ] && ! keystore=$(get_keystore); then
        log ERROR "Unable to determine the keystore path. Speicify the keystore with -k"
        return 1
    fi

    log INFO "keystore: $keystore"

    local pemfile
    for pemfile in "$ABCERT_PEMS_DIR"/*.pem; do
        alias=$(basename "${pemfile%.*}")
        keytool -importcert -keystore "$keystore" -file "$pemfile" -alias "$alias" \
            -storepass "$storepass" -noprompt
    done
}

argparse_install4j() {
    local keystore storepass
    while [ $# -gt 0 ]; do
        case "$1" in
            -k|--keystore)
                keystore=$2
                check_notempty "$keystore" --keystore || return
                shift 2
                ;;
            -p|--storepass)
                storepass=$2
                check_notempty "$storepass" --storepass || return
                shift 2
                ;;
            -h|--help)
                eprint -n "$ABCERT_INSTALL4J_HELP"
                return
                ;;
            *)
                log ERROR "Unexpected argument: $1"
                return 1
                ;;
        esac
    done
    install_wrapper install4j "$keystore" "$storepass"
}

################################################################################
#  Command: test                                                               #
################################################################################

ABCERT_TEST_TIMEOUT=3

_PASSED=0
_FAILED=0
_SKIPPED=0

show_header() {
    eprint "[ TEST    ]" "${@:?}"
}

show_result() {
    if [ "$?" -ne 0 ]; then
        _FAILED=$((_FAILED + 1))
        color_eprint "\e[31m" -n "[  FAILED ]"
    else
        _PASSED=$((_PASSED + 1))
        color_eprint "\e[32m" -n "[  PASSED ]"
    fi
    eprint
}

show_skipped() {
    _SKIPPED=$((_SKIPPED + 1))
    color_eprint "\e[33m" "[ SKIPPED ]"
}

show_stat() {
    local printed=false
    if [ "$_FAILED" -gt 0 ]; then
        color_eprint "\e[31m" -n "$_FAILED failed"
        printed=true
    fi

    if [ "$_PASSED" -gt 0 ]; then
        [ "$printed" = true ] && eprint -n ", "
        color_eprint "\e[32m" -n "$_PASSED passed"
        printed=true
    fi

    if [ "$_SKIPPED" -gt 0 ]; then
        [ "$printed" = true ] && eprint -n ", "
        color_eprint "\e[33m" -n "$_SKIPPED skipped"
        printed=true
    fi

    eprint
}

run_curl() {
    curl -sS --connect-timeout "$ABCERT_TEST_TIMEOUT" -I "${1:?}" > /dev/null
}

run_wget() {
    local output status
    output=$(wget -nv --spider --connect-timeout "$ABCERT_TEST_TIMEOUT" -t 1 "${1:?}" 2>&1)
    status=$?
    if [ "$status" -ne 0 ]; then
        eprint "$output"
        return "$status"
    fi
}

test_with() {
    local tool=${1:?}
    local tool_available
    which "$tool" >/dev/null 2>&1 && tool_available=true || tool_available=false

    show_header "Access older app with $tool"
    if [ "$tool_available" != true ]; then
        eprint "$tool not available"
        show_skipped
    else
        run_"$tool" "https://mirrors.tools.huawei.com/"
        show_result
    fi

    show_header "Access newer app with $tool"
    if [ "$tool_available" != true ]; then
        eprint "$tool not available"
        show_skipped
    else
        run_"$tool" "https://swinfotree.clouddragon.huawei.com/"
        show_result
    fi

    show_header "Access external link through proxy with $tool"
    if [ "$tool_available" != true ]; then
        eprint "$tool not available"
        show_skipped
    elif [ -z "$ABCERT_TEST_PROXY_NAME" ] || [ -z "$ABCERT_TEST_PROXY_PASSWORD" ]; then
        eprint "Proxy configuration not available"
        eprint "Set the following environment variables to enable the current test"
        eprint "  ABCERT_TEST_PROXY_NAME"
        eprint "  ABCERT_TEST_PROXY_PASSWORD"
        show_skipped
    else
        local auth="$ABCERT_TEST_PROXY_NAME:$ABCERT_TEST_PROXY_PASSWORD"
        export https_proxy="http://$auth@proxyhk.huawei.com:8080"
        run_"$tool" "https://github.com/"
        show_result
        unset https_proxy
    fi
}

runtest() {
    unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY
    test_with curl
    test_with wget

    eprint
    show_stat

    if [ "$_FAILED" -gt 0 ]; then
        return 1
    fi
}

argparse_test() {
    local color=auto
    while [ $# -gt 0 ]; do
        case "$1" in
            --color)
                color=$2
                check_notempty "$color" --color || return
                shift 2
                ;;
            -h|--help)
                eprint -n "$ABCERT_TEST_HELP"
                return
                ;;
            *)
                log ERROR "Unexpected argument: $1"
                return 1
                ;;
        esac
    done

    if [ "$color" = auto ]; then
        [ -t 1 ] && color=true || color=false
    elif [ "$color" != true ] && [ "$color" != false ]; then
        log ERROR "Invalid argument '$color' for --color"
        return 1
    fi
    ABCERT_COLOR="$color"

    runtest
}

main() {
    local command=$1
    shift
    case "$command" in
        install)
            argparse_install "$@"
            ;;
        install4j)
            argparse_install4j "$@"
            ;;
        test)
            argparse_test "$@"
            ;;
        version)
            echo "$ABCERT_VERSION"
            ;;
        -h|--help|help|"")
            eprint -n "$ABCERT_HELP"
            ;;
        *)
            log ERROR "Invalid command: $command. See '$ABCERT_NAME --help'"
            return 1
    esac
}

main "$@"
